package com.twofasapp.services.backup.models

enum class RemoteBackupErrorType(val code: Int) {
    UNKNOWN(1),
    NETWORK_UNAVAILABLE(2),
    GOOGLE_USER_PERMISSION_DENIED(3),
    GOOGLE_PLAY_SERVICES_UNAVAILABLE(4),
    GOOGLE_AUTH_FAILURE(5),
    JSON_PARSING_FAILURE(6),
    SYNC_FAILURE(7),
    HTTP_API_FAILURE(8),
    FILE_NOT_FOUND(9),
    CREDENTIALS_NOT_FOUND(10),
    ENCRYPT_UNKNOWN_FAILURE(11),
    DECRYPT_NO_PASSWORD(12),
    DECRYPT_WRONG_PASSWORD(13),
    DECRYPT_UNKNOWN_FAILURE(14),
}