package com.twofasapp.designsystem

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import androidx.compose.ui.res.painterResource

@Immutable
@Stable
/*
    Material Symbols, Rounded, NoFill, 600
 */
object TwIcons {
    val Placeholder @Composable get() = painterResource(R.drawable.ic_placeholder)
    val ArrowBack @Composable get() = painterResource(R.drawable.ic_arrow_back)
    val More @Composable get() = painterResource(R.drawable.ic_more)
    val Home @Composable get() = painterResource(R.drawable.ic_home)
    val HomeFilled @Composable get() = painterResource(R.drawable.ic_home_filled)
    val ExternalLink @Composable get() = painterResource(R.drawable.ic_external_link)
    val Notification @Composable get() = painterResource(R.drawable.ic_notification)
    val NotificationFilled @Composable get() = painterResource(R.drawable.ic_notification_filled)
    val Settings @Composable get() = painterResource(R.drawable.ic_settings)
    val SettingsFilled @Composable get() = painterResource(R.drawable.ic_settings_filled)
    val Edit @Composable get() = painterResource(R.drawable.ic_edit)
    val Qr @Composable get() = painterResource(R.drawable.ic_qr)
    val Write @Composable get() = painterResource(R.drawable.ic_write)
    val Licenses @Composable get() = painterResource(R.drawable.ic_licenses)
    val Lock @Composable get() = painterResource(R.drawable.ic_lock)
    val LockOpen @Composable get() = painterResource(R.drawable.ic_lock_open)
    val Share @Composable get() = painterResource(R.drawable.ic_share)
    val Terms @Composable get() = painterResource(R.drawable.ic_terms)
    val DragHandle @Composable get() = painterResource(R.drawable.ic_drag_handle)
    val Add @Composable get() = painterResource(R.drawable.ic_add)
    val CloudUpload @Composable get() = painterResource(R.drawable.ic_cloud_upload)
    val Cloud @Composable get() = painterResource(R.drawable.ic_cloud)
    val CloudOff @Composable get() = painterResource(R.drawable.ic_cloud_off)
    val Delete @Composable get() = painterResource(R.drawable.ic_delete)
    val Extension @Composable get() = painterResource(R.drawable.ic_extension)
    val Eye @Composable get() = painterResource(R.drawable.ic_eye)
    val EyeSlash @Composable get() = painterResource(R.drawable.ic_eye_slash)
    val Favorite @Composable get() = painterResource(R.drawable.ic_favorite)
    val Download @Composable get() = painterResource(R.drawable.ic_download)
    val Info @Composable get() = painterResource(R.drawable.ic_info)
    val Security @Composable get() = painterResource(R.drawable.ic_security)
    val Support @Composable get() = painterResource(R.drawable.ic_support)
    val Copy @Composable get() = painterResource(R.drawable.ic_copy)
    val Passcode @Composable get() = painterResource(R.drawable.ic_passcode)
    val Refresh @Composable get() = painterResource(R.drawable.ic_refresh)
    val Warning @Composable get() = painterResource(R.drawable.ic_warning)
    val Time @Composable get() = painterResource(R.drawable.ic_time)
    val Fingerprint @Composable get() = painterResource(R.drawable.ic_fingerprint)
    val Theme @Composable get() = painterResource(R.drawable.ic_theme)
    val NextToken @Composable get() = painterResource(R.drawable.ic_next_token)
    val ChevronDown @Composable get() = painterResource(R.drawable.ic_chevron_down)
    val ChevronUp @Composable get() = painterResource(R.drawable.ic_chevron_up)
    val ChevronRight @Composable get() = painterResource(R.drawable.ic_chevron_right)
    val ChevronLeft @Composable get() = painterResource(R.drawable.ic_chevron_left)
    val ArrowUpward @Composable get() = painterResource(R.drawable.ic_arrow_upward)
    val ArrowDownward @Composable get() = painterResource(R.drawable.ic_arrow_downward)
    val Sort @Composable get() = painterResource(R.drawable.ic_sort)
    val AddGroup @Composable get() = painterResource(R.drawable.ic_add_group)
    val Search @Composable get() = painterResource(R.drawable.ic_search)
    val Close @Composable get() = painterResource(R.drawable.ic_close)
    val ListStyle @Composable get() = painterResource(R.drawable.ic_list_style)
    val IncrementHotp @Composable get() = painterResource(R.drawable.ic_increment_hotp)
    val Screenshot @Composable get() = painterResource(R.drawable.ic_screenshot)
    val Keyboard @Composable get() = painterResource(R.drawable.ic_keyboard)
    val Panorama @Composable get() = painterResource(R.drawable.ic_panorama)
    val Guide @Composable get() = painterResource(R.drawable.ic_guide)
    val Export @Composable get() = painterResource(R.drawable.ic_export)
    val Import @Composable get() = painterResource(R.drawable.ic_import)
    val Backspace @Composable get() = painterResource(R.drawable.ic_backspace)
    val PinCode @Composable get() = painterResource(R.drawable.ic_pin_code)
    val Stop @Composable get() = painterResource(R.drawable.ic_stop)
    val Change @Composable get() = painterResource(R.drawable.ic_change)
    val Check @Composable get() = painterResource(R.drawable.ic_done)
    val Circle @Composable get() = painterResource(R.drawable.ic_circle)
    val CheckCircle @Composable get() = painterResource(R.drawable.ic_check_circle)
    val ErrorCircle @Composable get() = painterResource(R.drawable.ic_error_circle)
    val Stub @Composable get() = painterResource(R.drawable.ic_stub)
}