pluginManagement {
    includeBuild("buildlogic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        jcenter()
        maven { url = uri("https://jitpack.io") }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url = uri("https://jitpack.io") }
    }
}
rootProject.name = "2fas-android"
include(":truetime")
include(":truetime-rx")
include(":spanner")
include(":app")
include(":browserextension")
include(":base")
include(":prefs")
include(":serialization")
include(":di")
include(":time")
include(":parsers")
include(":resources")
include(":extensions")
include(":design")
include(":permissions")
include(":environment")
include(":network")
include(":push")
include(":persistence")
include(":qrscanner")
include(":about")
include(":settings")
include(":widgets")
include(":services")
include(":services:domain")
include(":widgets:domain")
include(":notifications")
include(":navigation")
include(":backup")
include(":core")
include(":featuretoggle")
include(":developer")
include(":backup:domain")
include(":security")
include(":security:domain")
include(":start")
include(":start:domain")
include(":time:domain")
include(":externalimport")
include(":browserextension:domain")
include(":data:session")
include(":core:storage")
include(":core:common")
include(":core:designsystem")
include(":feature:startup")
include(":core:locale")
include(":feature:home")
