[versions]
agp = "9.3.0"
cameraX = "1.6.1"
coil = "3.5.0"
composeActivity = "1.13.0"
composeNavigation = "2.9.8"
composeBom = "2026.06.01"
credentials = "1.6.0"
firebase = "34.16.0"
elmyr = "1.3.4"
koin = "4.2.2"
kotlin = "2.4.10"
kotlinCoroutines = "1.11.0"
kotlinKsp = "2.3.9"
ktor = "3.5.1"
ktlint = "5.4.2"
lifecycle = "2.11.0"
room = "2.8.4"
pluto = "3.0.1"
revenuecat = "10.14.1"
junit = "4.13.2"
kotest = "6.2.3"
espresso = "3.7.0"
uiAndroid = "1.11.4"
aboutLibraries = "15.0.4"
kotlinxCollections = "0.5.1"
accompanist = "0.36.0"
commonmark = "0.27.0"
glance = "1.1.1"
core = "1.17.0"

[libraries]
appcompat = "androidx.appcompat:appcompat:1.7.1"
argon2 = "com.lambdapioneer.argon2kt:argon2kt:1.6.0"
autofill = "androidx.autofill:autofill:1.3.0"
barcodeScanning = "com.google.mlkit:barcode-scanning:17.3.0"
biometric = "androidx.biometric:biometric:1.4.0-alpha07"
camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
camera2Lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
camera2View = { module = "androidx.camera:camera-view", version.ref = "cameraX" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coilSvg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coilNetwork = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coilCacheControl = { module = "io.coil-kt.coil3:coil-network-cache-control", version.ref = "coil" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
composeNavigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
composeFoundation = { module = "androidx.compose.foundation:foundation" }
composeAnimation = { module = "androidx.compose.animation:animation" }
composeMaterial2 = { module = "androidx.compose.material:material" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }
composeMaterial3Window = { module = "androidx.compose.material3:material3-window-size-class" }
composeMaterial3Adaptive = "androidx.compose.material3.adaptive:adaptive:1.2.0"
composeUi = { module = "androidx.compose.ui:ui" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
credentialsPlayServices = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
coreSplash = "androidx.core:core-splashscreen:1.2.0"
colorPicker = "com.github.skydoves:colorpicker-compose:1.2.0"
dataStore = "androidx.datastore:datastore-preferences:1.2.1"
desugar = "com.android.tools:desugar_jdk_libs:2.1.5"
firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebaseMessaging = { module = "com.google.firebase:firebase-messaging" }
elmyrCore = { module = "com.github.xgouchet.Elmyr:core", version.ref = "elmyr" }
elmyrJunit4 = { module = "com.github.xgouchet.Elmyr:junit4", version.ref = "elmyr" }
googleApiClientAndroid = "com.google.api-client:google-api-client-android:2.9.0"
googleAuth = "com.google.android.gms:play-services-auth:21.6.0"
googleDrive = "com.google.apis:google-api-services-drive:v3-rev20250717-2.0.0"
googleId = "com.google.android.libraries.identity.googleid:googleid:1.2.0"
googleApiHttpClientFork = "com.github.cryptomator:google-http-java-client:1.44.2-dev.0001"
javaxInject = "javax.inject:javax.inject:1"
koinCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinSerialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0"
ktorAuth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktorContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorKotlinSerialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorWebSockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycleCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycleComposeRuntime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycleLifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleProcess = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycleSavedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lottie = "com.airbnb.android:lottie-compose:6.7.1"
material = "com.google.android.material:material:1.14.0"
opencsv = "com.opencsv:opencsv:5.12.0"
playServicesCorutines = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.11.0"
revenuecat = { module = "com.revenuecat.purchases:purchases", version.ref = "revenuecat" }
revenuecatUi = { module = "com.revenuecat.purchases:purchases-ui", version.ref = "revenuecat" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
timber = "com.jakewharton.timber:timber:5.0.1"
truetime = "com.github.instacart:truetime-android:4.0.0.alpha"
workManager = "androidx.work:work-runtime-ktx:2.11.2"
webkit = "androidx.webkit:webkit:1.16.0"
pdfbox = "com.tom-roush:pdfbox-android:2.0.27.0"
pluto = { module = "com.androidpluto:pluto", version.ref = "pluto" }
plutoNoOp = { module = "com.androidpluto:pluto-no-op", version.ref = "pluto" }
plutoRoom = { module = "com.androidpluto.plugins:rooms-db", version.ref = "pluto" }
plutoRoomNoOp = { module = "com.androidpluto.plugins:rooms-db-no-op", version.ref = "pluto" }
plutoDataStore = { module = "com.androidpluto.plugins:datastore-pref", version.ref = "pluto" }
plutoDataStoreNoOp = { module = "com.androidpluto.plugins:datastore-pref-no-op", version.ref = "pluto" }
plutoLogger = { module = "com.androidpluto.plugins:logger", version.ref = "pluto" }
plutoLoggerNoOp = { module = "com.androidpluto.plugins:logger-no-op", version.ref = "pluto" }
mockk = "io.mockk:mockk:1.14.11"
junit = { module = "junit:junit", version.ref = "junit" }
kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
turbine = "app.cash.turbine:turbine:1.2.1"
uiTestJunit = { module = "androidx.compose.ui:ui-test-junit4" }
uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
uiTestNavigation = { module = "androidx.navigation:navigation-testing", version.ref = "composeNavigation" }
uiTestRunner = "androidx.test:runner:1.7.0"
uiTestOrchestrator = "androidx.test:orchestrator:1.6.1"
testCore = "androidx.test:core:1.7.0"
robolectric = "org.robolectric:robolectric:4.16.1"
slf4jNoOp = "org.slf4j:slf4j-nop:2.0.18"
kotlinCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koinTestJunit = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
zxing = "com.google.zxing:core:3.5.4"
uiAndroid = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
aboutLibrariesCore = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutLibrariesCompose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
palette = "androidx.palette:palette:1.0.0"
playReview = "com.google.android.play:review-ktx:2.0.2"
kotlinxCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollections" }
accompanistNavigation = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanistPagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanistSystemUi = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
activityX = { module = "androidx.activity:activity-ktx", version.ref = "composeActivity" }
apacheCommonsCodec = "commons-codec:commons-codec:1.20.0"
core = { module = "androidx.core:core-ktx", version.ref = "core" }
commonmarkCore = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commonmarkLink = { module = "org.commonmark:commonmark-ext-autolink", version.ref = "commonmark" }
commonmarkStrikethrough = { module = "org.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
commonmarkTables = { module = "org.commonmark:commonmark-ext-gfm-tables", version.ref = "commonmark" }
composeUiUtil = { module = "androidx.compose.ui:ui-util" }
glanceWidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
googleApiClientGson = "com.github.cryptomator:google-http-java-client:1.44.2-dev.0001"
playReviewKtx = "com.google.android.play:review-ktx:2.0.2"
playUpdate = "com.google.android.play:app-update:2.1.0"
playUpdateKtx = "com.google.android.play:app-update-ktx:2.1.0"
playFeatureDelivery = "com.google.android.play:feature-delivery-ktx:2.1.0"
protobuf = "com.google.protobuf:protobuf-kotlin-lite:4.33.0"
reLinker = "com.getkeepsafe.relinker:relinker:1.4.5"
securityCrypto = "androidx.security:security-crypto:1.1.0"
sqlCipher = "net.zetetic:sqlcipher-android:4.11.0"

[bundles]
aboutLibraries = [
    "aboutLibrariesCore",
    "aboutLibrariesCompose",
]
accompanist = [
    "accompanistNavigation",
    "accompanistPagerIndicators",
    "accompanistPermissions",
    "accompanistSystemUi",
]
appCompat = [
    "appcompat",
    "core",
]
commonmark = [
    "commonmarkCore",
    "commonmarkLink",
    "commonmarkStrikethrough",
    "commonmarkTables",
]
glance = [
    "glanceWidget",
]
playReview = [
    "playReviewKtx",
]
playUpdate = [
    "playUpdate",
    "playUpdateKtx",
]
barcodeScanner = [
    "barcodeScanning",
    "camera2",
    "camera2Lifecycle",
    "camera2View",
]
coil = [
    "coil",
    "coilSvg",
    "coilNetwork",
    "coilCacheControl"
]
compose = [
    "composeFoundation",
    "composeActivity",
    "composeAnimation",
    "composeMaterial2",
    "composeMaterial3",
    "composeMaterial3Window",
    "composeMaterial3Adaptive",
    "composeNavigation",
    "composeUi",
    "composeUiTooling",
    "composeUiUtil",
    "material",
    "kotlinxCollections"
]
elmyr = [
    "elmyrCore",
    "elmyrJunit4",
]
koin = [
    "koinCompose",
]
ktor = [
    "ktorAuth",
    "ktorContentNegotiation",
    "ktorCore",
    "ktorKotlinSerialization",
    "ktorLogging",
    "ktorOkhttp",
    "ktorWebSockets",
]
room = [
    "roomKtx",
    "roomRuntime",
    "sqlCipher",
]
viewModel = [
    "lifecycle",
    "lifecycleCompose",
    "lifecycleComposeRuntime",
    "lifecycleLifecycle",
    "lifecycleProcess",
    "lifecycleSavedstate",
]

[plugins]
agpApplication = { id = "com.android.application", version.ref = "agp" }
agpLibrary = { id = "com.android.library", version.ref = "agp" }
gradleVersions = "com.github.ben-manes.versions:0.52.0"
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
protobuf = "com.google.protobuf:0.10.0"
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinComposeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = { id = "org.jmailen.kotlinter", version.ref = "ktlint" }
twofasAndroidApplication = "twofas.androidApplication:unspecified"
twofasAndroidLibrary = "twofas.androidLibrary:unspecified"
twofasCompose = "twofas.compose:unspecified"
twofasLint = "twofas.lint:1"
twofasArtifactsCopy = "twofas.artifactsCopy:1"
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:0.8.5"
