blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/q4cP6qh2g5
    about: Need support or have a question? Our Discord members are there to help!
  - name: Reddit
    url: https://www.reddit.com/r/2fas_com/
    about: For discussions and questions.