name: ⭐ Feature request
description: Request a feature or enhancement.
title: 'feat: '
labels: ['Feature']
body:
  - type: markdown
    attributes:
      value: |
        Before creating a feature request, please ensure that it is not a duplicate of an existing feature request. You can review existing feature requests [here](https://github.com/twofas/2fas-android/labels/Feature).
  - type: textarea
    attributes:
      label: Feature description
      description: |
        - Describe the feature in detail
        - Add images, videos, links, examples, etc. if necessary
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why should this feature be implemented?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your feature request will be closed if you don't follow the checklist below.
      options:
        - label: This issue is not a duplicate of an existing feature request.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
