name: ❓ Question
description: Ask a question to the developers.
labels: ['Question']
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please ensure that it has not already been asked. You can review existing questions [here](https://github.com/twofas/2fas-android/labels/Question).
  - type: textarea
    attributes:
      label: Question
      description: |
        - Explain your question clearly and in detail
        - Add images and videos if necessary
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your question will be closed if you don't follow the checklist below.
      options:
        - label: This issue is not a duplicate of an existing question.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
