package com.twofasapp.core.design

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import androidx.compose.ui.res.painterResource

/**
 * Material Symbols (new), weight=400, fill=0, grade=0, optical size=24
 */

@Immutable
@Stable
object MdtIcons {
    val Add @Composable get() = painterResource(R.drawable.ic_add)
    val AddGroup @Composable get() = painterResource(R.drawable.ic_add_group)
    val ArrowBack @Composable get() = painterResource(R.drawable.ic_arrow_back)
    val ArrowDownward @Composable get() = painterResource(R.drawable.ic_arrow_downward)
    val ArrowUpward @Composable get() = painterResource(R.drawable.ic_arrow_upward)
    val Backspace @Composable get() = painterResource(R.drawable.ic_backspace)
    val Check @Composable get() = painterResource(R.drawable.ic_check)
    val CheckAll @Composable get() = painterResource(R.drawable.ic_check_all)
    val ChevronDown @Composable get() = painterResource(R.drawable.ic_chevron_down)
    val ChevronLeft @Composable get() = painterResource(R.drawable.ic_chevron_left)
    val ChevronRight @Composable get() = painterResource(R.drawable.ic_chevron_right)
    val ChevronUp @Composable get() = painterResource(R.drawable.ic_chevron_up)
    val Circle @Composable get() = painterResource(R.drawable.ic_circle)
    val CircleFilled @Composable get() = painterResource(R.drawable.ic_circle_filled)
    val CircleCheck @Composable get() = painterResource(R.drawable.ic_circle_check)
    val CircleUncheck @Composable get() = painterResource(R.drawable.ic_circle)
    val Close @Composable get() = painterResource(R.drawable.ic_close)
    val Cloud @Composable get() = painterResource(R.drawable.ic_cloud)
    val CloudOff @Composable get() = painterResource(R.drawable.ic_cloud_off)
    val CloudUpload @Composable get() = painterResource(R.drawable.ic_cloud_upload)
    val Copy @Composable get() = painterResource(R.drawable.ic_copy)
    val Delete @Composable get() = painterResource(R.drawable.ic_delete)
    val DeleteForever @Composable get() = painterResource(R.drawable.ic_delete_forever)
    val Download @Composable get() = painterResource(R.drawable.ic_download)
    val DragHandle @Composable get() = painterResource(R.drawable.ic_drag_handle)
    val Edit @Composable get() = painterResource(R.drawable.ic_edit)
    val Error @Composable get() = painterResource(R.drawable.ic_error)
    val Export @Composable get() = painterResource(R.drawable.ic_export)
    val Extension @Composable get() = painterResource(R.drawable.ic_extension)
    val ExternalLink @Composable get() = painterResource(R.drawable.ic_external_link)
    val Favorite @Composable get() = painterResource(R.drawable.ic_favorite)
    val Fingerprint @Composable get() = painterResource(R.drawable.ic_fingerprint)
    val Group @Composable get() = painterResource(R.drawable.ic_group)
    val Guide @Composable get() = painterResource(R.drawable.ic_guide)
    val Import @Composable get() = painterResource(R.drawable.ic_import)
    val Info @Composable get() = painterResource(R.drawable.ic_info)
    val Keyboard @Composable get() = painterResource(R.drawable.ic_keyboard)
    val Licenses @Composable get() = painterResource(R.drawable.ic_licenses)
    val Lock @Composable get() = painterResource(R.drawable.ic_lock)
    val LockOpen @Composable get() = painterResource(R.drawable.ic_lock_open)
    val LockoutTime @Composable get() = painterResource(R.drawable.ic_lockout_time)
    val Mobile @Composable get() = painterResource(R.drawable.ic_mobile)
    val More @Composable get() = painterResource(R.drawable.ic_more)
    val NextToken @Composable get() = painterResource(R.drawable.ic_next_token)
    val Notification @Composable get() = painterResource(R.drawable.ic_notification)
    val Panorama @Composable get() = painterResource(R.drawable.ic_panorama)
    val PinCode @Composable get() = painterResource(R.drawable.ic_pin_code)
    val Placeholder @Composable get() = painterResource(R.drawable.ic_placeholder)
    val Qr @Composable get() = painterResource(R.drawable.ic_qr)
    val Refresh @Composable get() = painterResource(R.drawable.ic_refresh)
    val Screenshot @Composable get() = painterResource(R.drawable.ic_screenshot)
    val Search @Composable get() = painterResource(R.drawable.ic_search)
    val SearchOff @Composable get() = painterResource(R.drawable.ic_search_off)
    val Security @Composable get() = painterResource(R.drawable.ic_security)
    val Settings @Composable get() = painterResource(R.drawable.ic_settings)
    val SettingsFilled @Composable get() = painterResource(R.drawable.ic_settings_filled)
    val Share @Composable get() = painterResource(R.drawable.ic_share)
    val Sort @Composable get() = painterResource(R.drawable.ic_sort)
    val Star @Composable get() = painterResource(R.drawable.ic_star)
    val StarShine @Composable get() = painterResource(R.drawable.ic_star_shine)
    val Stop @Composable get() = painterResource(R.drawable.ic_stop)
    val Stub @Composable get() = painterResource(R.drawable.ic_stub)
    val Support @Composable get() = painterResource(R.drawable.ic_support)
    val Terms @Composable get() = painterResource(R.drawable.ic_terms)
    val Theme @Composable get() = painterResource(R.drawable.ic_theme)
    val Tokens @Composable get() = painterResource(R.drawable.ic_tokens)
    val TokensFilled @Composable get() = painterResource(R.drawable.ic_tokens_filled)
    val UnfoldMore @Composable get() = painterResource(R.drawable.ic_unfold_more)
    val Visibility @Composable get() = painterResource(R.drawable.ic_visibility)
    val VisibilityOff @Composable get() = painterResource(R.drawable.ic_visibility_off)
    val Warning @Composable get() = painterResource(R.drawable.ic_warning)
    val WriteReview @Composable get() = painterResource(R.drawable.ic_write_review)
}